export const adjectives = [
    "Tea", "Teafy", "Steamy", "Hot", "Icy", "Chill", "Bold", "Mystic", "Royal", "Zen",
    "Ancient", "Fresh", "Golden", "Green", "Black", "White", "Oolong", "Crisp", "Magic", "Turbo",
    "Quantum", "Meta", "Cyber", "Neo", "Ultra", "Secret", "Smooth", "Creamy", "Brewed", "Smoky",
    "Wild", "Earthy", "Flowing", "Dripped", "Infused", "Sipped", "Lush", "Dreamy", "Divine", "Elixir",
    "Herbal", "Silky", "Cloudy", "Gentle", "Rare", "Epic", "Sweet", "Savage", "Glacial", "Power",
    "Celestial", "Luminous", "Alpine", "Crystal", "Eternal", "Tasty", "Misty", "Velvet", "Cocoa",
    "Brewster", "Steeper", "Swirl", "Blissful", "Serene", "Frosted", "Charmed", "Steeped", "Soothing",
    "Soothe", "Breezy", "Mellow", "Flowery", "Vibrant", "Fire", "Vivid", "Noble",
    "Refreshing", "Sublime", "Delightful", "Fragrant", "Classic", "Fluffy", "Frisky", "Heavenly",
    "Sunny", "Wholesome", "Aromatic", "Thirsty", "Rich", "Boldly", "Charming", "Zesty", "Tart",
    "Wildly", "Smoothly", "Bitterly", "Spicy", "Crisply", "Deeply", "Calming", "Pure", "Untamed",
    "Ethereal", "Whispering", "Radiant", "Glimmering", "Sparkling", "Velvet", "Glistening", "Shimmering",
    "Velvety", "Lively", "Vivid", "Brilliant", "Radiant", "Dazzling", "Gleaming", "Lustrous",
    "Polished", "Sleek", "Silken", "Flowing", "Gentle", "Soft", "Muted", "Subtle", "Faint",
    "Bright", "Bold", "Sharp", "Crisp", "Clean", "Clear", "Vibrant", "Intense", "Deep",
    "Dark", "Light", "Pale", "Faded", "Misty", "Hazy", "Smoky", "Cloudy", "Shadowy",
    "Glowing", "Luminous", "Shining", "Beaming", "Fiery", "Flaming", "Fiery", "Burning", "Blazing",
    "Warm", "Hot", "Cool", "Cold", "Icy", "Frosty", "Chilly", "Arctic", "Glacial",
    "Smooth", "Rough", "Gritty", "Coarse", "Fine", "Delicate", "Robust", "Sturdy", "Solid",
    "Fluid", "Liquid", "Melted", "Molten", "Solidified", "Crystalized", "Powdery", "Dusty", "Grainy",
    "Sweet", "Sour", "Bitter", "Salty", "Umami", "Spicy", "Savory", "Tangy", "Tart",
    "Fruity", "Floral", "Earthy", "Woody", "Herbal", "Minty", "Citrusy", "Nutty", "Creamy",
    "Velvet", "Silky", "Smooth", "Creamy", "Rich", "Buttery", "Fluffy", "Puffy", "Airy",
    "Light", "Heavy", "Dense", "Sparse", "Thick", "Thin", "Wide", "Narrow", "Tall",
    "Short", "Long", "Round", "Square", "Angular", "Curved", "Straight", "Zigzag", "Wavy",
    "Silent", "Loud", "Noisy", "Quiet", "Whispering", "Humming", "Buzzing", "Chirping", "Singing",
    "Happy", "Sad", "Angry", "Calm", "Excited", "Peaceful", "Joyful", "Serene", "Dreamy",
    "Mysterious", "Enigmatic", "Secretive", "Hidden", "Obscure", "Covert", "Stealthy", "Clandestine",
    "Ancient", "Old", "New", "Modern", "Future", "Past", "Timeless", "Eternal", "Brief",
    "Quick", "Slow", "Fast", "Rapid", "Swift", "Nimble", "Agile", "Graceful", "Fluid",
    "Strong", "Weak", "Fraile", "Robust", "Sturdy", "Solid", "Tough", "Resilient", "Durable",
    "Brave", "Cowardly", "Fearless", "Bold", "Courageous", "Daring", "Heroic", "Valiant", "Gallant",
    "Wise", "Foolish", "Clever", "Intelligent", "Smart", "Brilliant", "Genius", "Shrewd", "Astute",
    "Kind", "Cruel", "Gentle", "Harsh", "Soft", "Tender", "Loving", "Caring", "Compassionate",
    "True", "False", "Real", "Fake", "Authentic", "Genuine", "Bogus", "Sham", "Counterfeit",
    "Open", "Closed", "Wide", "Narrow", "Spacious", "Confined", "Vast", "Immense", "Tiny",
    "Big", "Small", "Large", "Little", "Huge", "Giant", "Minute", "Petite", "Micro",
    "Good", "Bad", "Evil", "Moral", "Immoral", "Virtuous", "Sinful", "Righteous", "Wicked",
    "Hot", "Cold", "Warm", "Cool", "Freezing", "Boiling", "Lukewarm", "Chilly", "Icy",
    "Wet", "Dry", "Damp", "Moist", "Soggy", "Parched", "Arid", "Humid", "Sticky",
    "Bright", "Dim", "Luminous", "Dark", "Gloomy", "Shining", "Sparkling", "Radiant", "Gleaming",
    "Smooth", "Rough", "Slippery", "Bumpy", "Uneven", "Polished", "Gritty", "Coarse", "Fine",
    "Soft", "Hard", "Firm", "Squishy", "Rigid", "Flexible", "Pliable", "Elastic", "Stiff",
    "Fast", "Slow", "Quick", "Rapid", "Swift", "Lethargic", "Sluggish", "Dilatory", "Tardy",
    "Happy", "Sad", "Joyful", "Sorrowful", "Cheerful", "Gloomy", "Optimistic", "Pessimistic", "Hopeful",
    "Fearful", "Brave", "Cowardly", "Courageous", "Anxious", "Calm", "Relaxed", "Stressed", "Tense",
    "Angry", "Peaceful", "Furious", "Calm", "Annoyed", "Serene", "Tranquil", "Rage", "Ire",
    "Confused", "Clear", "Muddled", "Lucid", "Perplexed", "Simple", "Complex", "Intricate", "Obvious",
    "Curious", "Indifferent", "Inquisitive", "Apathetic", "Interested", "Uncaring", "Concerned", "Detached", "Aloof",
    "Lazy", "Energetic", "Slothful", "Vigorous", "Active", "Dynamic", "Lethargic", "Spirited", "Animated",
    "Loyal", "Disloyal", "Faithful", "Traitorous", "Devoted", "Treacherous", "Constant", "Fickle", "Steady",
    "Proud", "Humble", "Arrogant", "Modest", "Confident", "Shy", "Boastful", "Meek", "Conceited",
    "Rich", "Poor", "Wealthy", "Impoverished", "Affluent", "Destitute", "Prosperous", "Needy", "Opulent",
    "Clean", "Dirty", "Spotless", "Filthy", "Pure", "Sullied", "Tidy", "Messy", "Grimey",
    "Hot", "Cold", "Warm", "Cool", "Freezing", "Boiling", "Chilly", "Icy", "Scorching",
    "Open", "Closed", "Wide", "Narrow", "Spacious", "Confined", "Expansive", "Cramped", "Vast",
    "Healthy", "Sick", "Well", "Ill", "Robust", "Frail", "Vigorous", "Weak", "Ailing",
    "Light", "Heavy", "Feathery", "Bulky", "Airy", "Dense", "Weighty", "Massive", "Tiny",
    "Sweet", "Sour", "Bitter", "Salty", "Spicy", "Mild", "Strong", "Pungent", "Zesty",
    "Ancient", "Modern", "Timeless", "Future", "Past", "Historic", "Contemporary", "Classic", "Vintage",
    "Silent", "Loud", "Quiet", "Noisy", "Whispering", "Roaring", "Soft", "Harsh", "Muffled",
    "Graceful", "Clumsy", "Elegant", "Awkward", "Poised", "Gaucheness", "Nimble", "Stumbling", "Fluid",
    "Generous", "Stingy", "Giving", "Selfish", "Kind", "Greedy", "Altruistic", "Avaricious", "Benevolent",
    "Honest", "Dishonest", "Truthful", "Deceptive", "Sincere", "Lying", "Candid", "False", "Upright"
];

export const nouns = [
    "Tea", "Drop", "Brew", "Cup", "Pot", "Leaf", "Leaves", "Stream", "Chain",
    "Node", "Spirit", "Storm", "Wave", "Time", "Flow", "Bliss", "Leaflet", "Dust", "Shot",
    "Dash", "Blend", "Tonic", "Infusion", "Splash", "Sprout", "Root", "Elixir", "Brewer", "Bag",
    "Whirl", "Aura", "Chalice", "Flame", "Spark", "Steam", "Frost", "Bloom", "Essence", "Origin",
    "Whisp", "Whirlwind", "Burst", "Pulse", "Crush", "Crave", "Zone", "Realm", "Vortex", "Flavor",
    "Brewmaster", "Whisk", "Sprinkle", "Eruption", "Kettle", "Frosting", "Blooming", "Rush", "Vibe",
    "Citrus", "Essence", "Myst", "Potpourri", "Breeze", "Vapour", "Eclipse", "Leafage",
    "Harvest", "Nectar", "Journey", "Charm", "Perk", "Tide", "Brewtastic", "Gusto",
    "Dew", "Spritz", "Sipper", "Swirl", "Fruity", "Mix", "Classic", "Mystify", "Wave", "Tearise",
    "Chase", "Flick", "Bubbly", "Pour", "Refreshment", "Twirl", "Glam", "Whiz", "Zing", "Sage",
    "Swarm", "Storm", "Spice", "Taste", "Harmonic", "Soul", "Mist", "Reef", "Chime",
    "Echo", "Essence", "Night", "Fusion", "Fusionize", "Sip", "Kettle", "Brewtiful", "Swell",
    "Touch", "Savory", "Teaser", "Zest", "Splash", "Snap", "Brewgen", "Chime", "Sipify", "Cupful",
    "Infused", "Brewfinity", "Brewit", "Teacraft", "Flavorize", "Clarity", "Liquid", "Harmonic",
    "Potion", "Vibe", "Glow", "Twist", "Chillax", "Zenith", "Horizon", "Nebula", "Vapor", "Cascade",
    "Echo", "Whisper", "Glimmer", "Shimmer", "Spark", "Flash", "Beam", "Ray", "Glow", "Luster",
    "Silk", "Velvet", "Cream", "Foam", "Mousse", "Fluff", "Cloud", "Mist", "Haze", "Smoke",
    "Drop", "Ripple", "Drip", "Trickle", "Flow", "Stream", "River", "Lake", "Ocean", "Sea",
    "Mountain", "Peak", "Valley", "Forest", "Grove", "Wood", "Tree", "Leaf", "Blossom", "Flower",
    "Sun", "Moon", "Star", "Comet", "Galaxy", "Nebula", "Aurora", "Constellation", "Cosmos", "Universe",
    "Fire", "Flame", "Ember", "Spark", "Ash", "Blaze", "Inferno", "Cinder", "Glow", "Heat",
    "Ice", "Frost", "Snow", "Crystal", "Shard", "Chill", "Freeze", "Glacier", "Hoarfrost", "Rime",
    "Wind", "Breeze", "Gust", "Gale", "Storm", "Hurricane", "Typhoon", "Cyclone", "Tornado", "Zephyr",
    "Rain", "Shower", "Drizzle", "Downpour", "Torrent", "Flood", "Deluge", "Mist", "Fog", "Dew",
    "Lightning", "Thunder", "Bolt", "Strike", "Flash", "Crack", "Boom", "Rumble", "Roll", "Clap",
    "Dream", "Vision", "Fantasy", "Illusion", "Mirage", "Reverie", "Nightmare", "Daydream", "Whimsy",
    "Echo", "Resonance", "Reverb", "Vibration", "Hum", "Buzz", "Chime", "Tinkle", "Jingle", "Ring",
    "Whisper", "Murmur", "Mutter", "Rustle", "Swoosh", "Swish", "Crackle", "Pop", "Hiss", "Sizzle",
    "Pulse", "Beat", "Throb", "Rhythm", "Vibe", "Energy", "Aura", "Field", "Wave", "Frequency",
    "Key", "Lock", "Door", "Gate", "Path", "Road", "Trail", "Route", "Journey", "Quest",
    "Treasure", "Gem", "Jewel", "Crystal", "Gold", "Silver", "Copper", "Bronze", "Iron", "Steel",
    "Shield", "Sword", "Blade", "Armor", "Helmet", "Gauntlet", "Boot", "Glove", "Weapon", "Tool",
    "Core", "Heart", "Center", "Nucleus", "Essence", "Soul", "Spirit", "Mind", "Brain", "Thought",
    "Light", "Shadow", "Darkness", "Brightness", "Gloom", "Shine", "Sparkle", "Gleam", "Radiance", "Aura",
    "Star", "Planet", "Moon", "Sun", "Galaxy", "Nebula", "Comet", "Asteroid", "Meteor", "Cosmos",
    "Sky", "Heaven", "Cloud", "Air", "Atmosphere", "Firmament", "Horizon", "Zenith", "Nadir", "Apex",
    "Abyss", "Depth", "Chasm", "Void", "Hole", "Pit", "Cave", "Cavern", "Grotto", "Underworld",
    "Beacon", "Lantern", "Torch", "Flame", "Firefly", "Glowworm", "Luminary", "Flare", "Shine", "Radiant",
    "Whisper", "Murmur", "Secret", "Riddle", "Enigma", "Mystery", "Puzzle", "Conundrum", "Paradox", "Jigsaw",
    "Dream", "Vision", "Fantasy", "Illusion", "Hallucination", "Nightmare", "Reverie", "Daydream", "Figment",
    "Saga", "Legend", "Myth", "Tale", "Epic", "Story", "Chronicle", "Folklore", "Fable", "Narrative",
    "Dawn", "Dusk", "Twilight", "Morning", "Evening", "Noon", "Midnight", "Sunrise", "Sunset", "Daybreak",
    "Echo", "Reverberation", "Resonance", "Vibration", "Sound", "Noise", "Silence", "Quiet", "Hush",
    "Gate", "Doorway", "Portal", "Threshold", "Entrance", "Exit", "Archway", "Passage", "Gateway", "Chasm",
    "Cipher", "Code", "Enigma", "Crypt", "Rune", "Symbol", "Glyph", "Sign", "Mark", "Emblem",
    "Miracle", "Wonder", "Phenomenon", "Marvel", "Awe", "Astonishment", "Surprise", "Shock", "Delight",
    "Destiny", "Fate", "Fortune", "Karma", "Providence", "Serendipity", "Kismet", "Predestination", "Doom",
    "Harmony", "Melody", "Symphony", "Rhythm", "Tune", "Cadence", "Chorus", "Chord", "Octave", "Pitch",
    "Vessel", "Container", "Chalice", "Goblet", "Cup", "Bowl", "Jar", "Bottle", "Flask", "Canteen",
    "Nexus", "Core", "Hub", "Center", "Junction", "Crossroads", "Node", "Link", "Connection", "Tie",
    "Relic", "Artifact", "Ancient", "Memento", "Souvenir", "Keepsake", "Heirloom", "Antiquity", "Curio",
    "Sanctuary", "Refuge", "Haven", "Shelter", "Asylum", "Retreat", "Hideaway", "Nest", "Den", "Oasis",
    "Zenith", "Summit", "Apex", "Pinnacle", "Peak", "Acme", "Climax", "Crest", "Vertex", "Tiptop",
    "Whisperwind", "Starfall", "Moonbeam", "Sunburst", "Raindrop", "Cloudgate", "Firestorm", "Icepeak",
    "Shadowfall", "Lightbringer", "Dreamweaver", "Soulfire", "Everbloom", "Glimmerwood", "Ironheart",
    "Silvermist", "Goldwing", "Brightshard", "Darkbrew", "Crystalfall", "Deeproot", "Silentstream",
    "Ancientlight", "Mysticbrew", "Royalpeak", "Zenithflow", "Wildfire", "Earthbound", "Flowingriver",
    "Drippedgold", "Infusedspirit", "Sippeddream", "Lushvalley", "Dreamyforest", "Divineelixir",
    "Herbalsilence", "Silkycloud", "Gentlerain", "Raregem", "Epicquest", "Sweetbliss", "Savagepeak",
    "Glacialice", "Powercore", "Celestialaura", "Luminousstar", "Alpinecrystal", "Eternalflame",
    "Tastybrew", "Mistyshadow", "Velvetbloom", "Cocoanight", "Brewsterfire", "Steeperflow",
    "Swirlbliss", "Blissfulspirit", "Serenewave", "Frostedleaf", "Charmedlife", "Steepedsoul",
    "Soothingmist", "Soothebreeze", "Breezyflow", "Mellowleaf", "Flowerydream", "Fireglow",
    "Vividspark", "Noblepath", "Refreshingdrop", "Sublimewater", "Delightfulbrew", "Fragrantmist",
    "Classicblend", "Fluffycloud", "Friskyspirit", "Heavenlybrew", "Sunnyday", "Wholesomeheart",
    "Aromaticdrop", "Thirstybrew", "Richflavor", "Boldlyblend", "Charmingwave", "Zestydrop",
    "Tartfruit", "Wildlyroot", "Smoothlybrew", "Bitterlycold", "Spicydrop", "Crispnight",
    "Exoticbloom", "Zingydrop", "Gourmetbrew", "Deliciousmix", "Sippablebliss", "Luxuriousbrew",
    "Plushcloud", "Fizzybrew", "Freshlybrew", "Intenseflavor", "Savorydrop", "Vibrantlylight",
    "Tinglingbrew", "Lushlygreen", "Infusedmist", "Herbaliciousbrew", "Fragrantleaf", "Bitterbrew",
    "Livelyspark", "Sourdrop", "Sparklingmist", "Buzzybrew", "Flavorfulblend", "Livelydrop",
    "Wildishflower", "Hazybrew", "Whisperingwind", "Lightlymist", "Crisplydrop", "Deeplyroot",
    "Calmingbrew", "Pureheart", "Untamedspirit"
];
